# Anomalies

An anomaly is the difference of a given state of the climate compared to the present climate. To characterise the current climate, we use the following time period: 1981-2010.

We also focus on Europe: 25W-40E, 34N-72N.

In [1]:
# Standard imports
import numpy as np
import pandas as pd
import datetime as dt
import matplotlib.pyplot as plt
import xarray as xr

%matplotlib inline

In [23]:
# Open fwi.nc as dataset
ds = xr.open_dataset('/perm/mo/moc0/data/fwi_198001_201907_Europe.nc')
da = ds.fwi

In [3]:
# Calculate anomalies in units of standard deviations
dam = da.groupby('time.month')
clim_mean = dam.mean(dim = 'time', skipna = True)
clim_sd = dam.std(dim = 'time', skipna = True)
anom = (dam - clim_mean) / clim_sd
anom

/usr/local/apps/python3/3.6.9-01/lib/python3.6/site-packages/xarray/core/nanops.py:160: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)
/usr/local/apps/python3/3.6.9-01/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:1628: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)


<xarray.DataArray 'fwi' (time: 14457, lat: 135, lon: 231, month: 12)>
array([[[[-0.40609 , ..., -0.394107],
         ...,
         [      nan, ...,       nan]],

        ...,

        [[      nan, ...,       nan],
         ...,
         [-0.360697, ..., -0.308951]]],


       ...,


       [[[-6.374403, ..., -6.18631 ],
         ...,
         [      nan, ...,       nan]],

        ...,

        [[      nan, ...,       nan],
         ...,
         [-2.314685, ..., -1.982619]]]], dtype=float32)
Coordinates:
  * lon      (lon) float32 -24.75 -24.46875 -24.1875 ... 39.375 39.65625 39.9375
  * lat      (lat) float32 71.80322 71.522194 71.241165 ... 34.426216 34.145187
  * time     (time) datetime64[ns] 1980-01-01 1980-01-02 ... 2019-07-31
  * month    (month) int64 1 2 3 4 5 6 7 8 9 10 11 12

In [8]:
# Plot a random date
anom1 = anom[0,,,]
anom1.plot();

SyntaxError: invalid syntax (<ipython-input-8-89e2e9aa8688>, line 2)

In [19]:
clim_mean

<xarray.DataArray 'fwi' (month: 12, lat: 135, lon: 231)>
array([[[ 0.11937 ,  0.133628, ...,       nan,       nan],
        [ 0.182948,  0.167735, ...,       nan,       nan],
        ...,
        [      nan,       nan, ..., 11.802231, 12.690201],
        [      nan,       nan, ..., 13.947642, 14.156335]],

       [[ 0.112813,  0.124668, ...,       nan,       nan],
        [ 0.171649,  0.155016, ...,       nan,       nan],
        ...,
        [      nan,       nan, ..., 16.221844, 17.403269],
        [      nan,       nan, ..., 18.990257, 19.001852]],

       ...,

       [[ 0.143   ,  0.158682, ...,       nan,       nan],
        [ 0.227931,  0.209707, ...,       nan,       nan],
        ...,
        [      nan,       nan, ..., 25.391375, 26.33503 ],
        [      nan,       nan, ..., 27.222595, 27.187105]],

       [[ 0.15359 ,  0.168779, ...,       nan,       nan],
        [ 0.22991 ,  0.212691, ...,       nan,       nan],
        ...,
        [      nan,       nan, ..., 16.054852,

In [20]:
anom

<xarray.DataArray 'fwi' (time: 14457, lat: 135, lon: 231, month: 12)>
array([[[[-0.40609 , ..., -0.394107],
         ...,
         [      nan, ...,       nan]],

        ...,

        [[      nan, ...,       nan],
         ...,
         [-0.360697, ..., -0.308951]]],


       ...,


       [[[-6.374403, ..., -6.18631 ],
         ...,
         [      nan, ...,       nan]],

        ...,

        [[      nan, ...,       nan],
         ...,
         [-2.314685, ..., -1.982619]]]], dtype=float32)
Coordinates:
  * lon      (lon) float32 -24.75 -24.46875 -24.1875 ... 39.375 39.65625 39.9375
  * lat      (lat) float32 71.80322 71.522194 71.241165 ... 34.426216 34.145187
  * time     (time) datetime64[ns] 1980-01-01 1980-01-02 ... 2019-07-31
  * month    (month) int64 1 2 3 4 5 6 7 8 9 10 11 12